services:
  - type: web
    name: easy-build
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn conf.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: DATABASE_URL
        fromDatabase:
          name: easy-build-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: easy-build-db
    databaseName: easy_build
    user: easy_build_user
