services:
  - type: web
    name: easybuild
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT conf.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: '*'
