# Generated by Django 5.2.15 on 2026-06-22 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0002_builderprofile'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Xonasi', 'verbose_name_plural': 'Chat Xonalari'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='group_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='team_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='build.builderprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
