# Generated by Django 6.0.5 on 2026-06-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_group_name_chatroom_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
    ]
