# Generated by Django 6.0.5 on 2026-06-10 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_role_profile_avatar_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('tashkent_sh', 'Toshkent shahri'), ('tashkent_v', 'Toshkent viloyati'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fergana', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('kashkadarya', 'Qashqadaryo viloyati'), ('samarkand', 'Samarkand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('khorezm', 'Xorazm viloyati'), ('karakalpakstan', 'Qoraqalpogʻiston Respublikasi')], default='tashkent_sh', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Buyurtmachi (Mijoz)'), ('builder', 'Quruvchi (Usta)')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
