# Generated by Django 5.2.15 on 2026-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_bio_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('tashkent_sh', 'Toshkent shahri'), ('tashkent_v', 'Toshkent viloyati'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fergana', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('kashkadarya', 'Qashqadaryo viloyati'), ('samarkand', 'Samarkand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('khorezm', 'Xorazm viloyati'), ('karakalpakstan', 'Qoraqalpogʻiston Respublikasi')], default='tashkent_sh', max_length=50),
        ),
    ]
