# Generated by Django 6.0.5 on 2026-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('tashkent_sh', 'Toshkent shahri'), ('tashkent_v', 'Toshkent viloyati'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fergana', "Farg'ona viloyati"), ('jizzakh', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('kashkadarya', 'Qashqadaryo viloyati'), ('samarkand', 'Samarkand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('khorezm', 'Xorazm viloyati'), ('karakalpakstan', "Qoraqalpog'iston Respublikasi")], default='tashkent_sh', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
