# Generated by Django 6.0.5 on 2026-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, help_text='@username yoki t.me/username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Xalqaro formatda: +998901234567', max_length=20, null=True),
        ),
    ]
