# Generated by Django 6.0.5 on 2026-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_telegram_profile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Buyurtmachi (Mijoz)'), ('builder', 'Quruvchi (Usta)'), ('team', 'Qurilish jamoasi')], default='client', max_length=20),
        ),
    ]
