# Generated by Django 6.0.5 on 2026-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook profil linki yoki username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='@username yoki instagram profil linki', max_length=100, null=True),
        ),
    ]
