# Generated by Django 5.2.15 on 2026-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_facebook_profile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canceled_orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bekor qilingan buyurtmalar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tugatilgan buyurtmalar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan usta'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name="O'rtacha baho"),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text="O'rtacha javob berish vaqti (daqiqa)"),
        ),
    ]
