# Generated by Django 5.2.15 on 2026-07-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_premium_alter_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_messages',
            field=models.BooleanField(default=True, verbose_name='Yangi xabarlar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_orders',
            field=models.BooleanField(default=True, verbose_name='Yangi buyurtmalar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_promotions',
            field=models.BooleanField(default=False, verbose_name='Aksiya va chegirmalar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_system',
            field=models.BooleanField(default=True, verbose_name='Tizim xabarnomalari'),
        ),
    ]
