"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 6.0.5.

Barcha shaxsiy ma'lumotlar (parol, kalit va h.k.) .env faylidan o'qiladi.
Jamoangizga .env.example faylini ulashing, lekin .env faylini HECH QACHON
Git'ga push QILMANG — u .gitignore orqali himoyalangan.
"""

import os
import dj_database_url

from pathlib import Path
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _  # i18n uchun zarur import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env faylini yuklash
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://easy-build-bmz2.onrender.com',
    'https://*.onrender.com',
    'https://easy_build.com',
    'https://www.easy_build.com',
    'https://easybuild.com',
    'https://www.easybuild.com',
    'https://easybuild.uz',
    'https://www.easybuild.uz',
    'https://easy-build.com',
    'https://www.easy-build.com',
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'django.contrib.sites',
    'django.contrib.humanize',

    # Third Party Apps
    'channels',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'tailwind',

    # Local Apps ── TARTIBNI SHUNDAY O'ZGARTIRING:
    'build',                           # <── 'build' tepaga chiqdi (chat'dan oldin yuklanadi)
    'accounts.apps.AccountConfig',
    'chat',                            # <── 'chat' pastga tushdi
    'rest_framework',
]

# DEBUG rejimida brauzerni avtomatik yangilash (Live Reload) ilovasini qo'shish
if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Tillar uchun javobgar Middleware (Joylashuvi to'g'ri)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Allauth Middleware
    'allauth.account.middleware.AccountMiddleware',
    # Subscription expiry auto-check
    'build.middleware.SubscriptionExpiryMiddleware',
    'build.middleware.MaintenanceModeMiddleware',
    'build.middleware.AuditLogMiddleware',
]

# DEBUG rejimida brauzerni avtomatik yangilash middleware'ini qo'shish
if DEBUG:
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chat.context_processors.unread_messages_count',
                'build.context_processors.notifications_processor',
                'build.context_processors.subscription_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'
ASGI_APPLICATION = 'conf.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"postgres://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', '')}@{os.getenv('DB_HOST', '127.0.0.1')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'easy_build')}",
        conn_max_age=600
    )
}

# ── Django Channels — InMemory (development) / Redis (production) ──
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')

CHANNEL_LAYERS = {
    'default': {
        # Production uchun: channels_redis.core.RedisChannelLayer
        # Development uchun: channels.layers.InMemoryChannelLayer
        'BACKEND': os.getenv(
            'CHANNEL_LAYER_BACKEND',
            'channels.layers.InMemoryChannelLayer'
        ),
        # Redis ishlatganda quyidagi CONFIG ni aktivlashtiring:
        # 'CONFIG': {
        #     'hosts': [REDIS_URL],
        # },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization (Tillarni Sozlash)
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', _("O'zbekcha")),
    ('ru', _('Русский')),
    ('en', _('English')),
]

TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Tillar almashtirilganda xotirada saqlanib qolishi uchun Cookie nomi
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000 # Cookie 1 yil davomida saqlanadi


# Django Allauth & Sites Sozlamalari
SITE_ID = int(os.getenv('SITE_ID', '1'))

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SiteFallbackSocialAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # client_id va secret DB da (socialaccount_socialapp jadvali) saqlanadi
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media fayllar uchun (Rasm, fayl yuklash uchun)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tailwind va avtomatik yuklanish ilovasi nomi
TAILWIND_APP_NAME = "templates"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / 'staticfiles'
